import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Cart | Checkout",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    storageKey="theme"
                    enableSystem
                    disableTransitionOnChange
                >
                    <ClerkProvider>
                        <div className="min-h-screen">
                            <Navbar />
                            <main className="py-8 max-w-7xl mx-auto px-4">
                                <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
                                    <div className="hidden lg:block lg:col-span-3">
                                        sidebar
                                    </div>
                                    <div className="lg:col-span-9">
                                        {children}
                                    </div>
                                </div>
                            </main>
                        </div>
                    </ClerkProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
